# Generated by Django 5.1.2 on 2024-10-27 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_menu', models.CharField(max_length=255)),
                ('cluster', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_restoran', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=255)),
                ('jenis_suasana', models.CharField(max_length=255)),
                ('keramaian_restoran', models.IntegerField()),
                ('jenis_penyajian', models.CharField(max_length=255)),
                ('ayce_atau_alacarte', models.CharField(max_length=255)),
                ('harga_rata_rata_makanan', models.IntegerField()),
                ('gambar', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('pesan_rating', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_ratings', to=settings.AUTH_USER_MODEL)),
                ('restaurant_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
