# Generated by Django 5.1.2 on 2024-10-27 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_alter_ratings_restaurant_review'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuWithLikes',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ratings.menu')),
                ('likes', models.IntegerField(default=0)),
            ],
            bases=('ratings.menu',),
        ),
    ]
