# Generated by Django 5.1.2 on 2024-10-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_menuwithlikes_likes_menuwithlikes_liked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuWithLikes',
        ),
    ]
